Repository aazuspan/sankee, pull requests merged in 2025-06, with the labels that each got.

#59 Dataset updates
  sankee/datasets.py
  tests/test_datasets.py
  tests/test_plotting.py
Labels: enhancement

#61 Allow using unlisted dataset years
  sankee/datasets.py
  sankee/sampling.py
  tests/test_datasets.py
Labels: enhancement

#62 Catch missing years for LCMS and CCAP
  sankee/datasets.py
  sankee/sampling.py
  tests/test_datasets.py
Labels: bug

#64 Add GLC FCS30D datasets to premade datasets
  sankee/datasets.py
  tests/test_datasets.py
Labels: enhancement

#65 Update dataset table
  docs/sankee.rst
  pyproject.toml
Labels: documentation
